listen: "0.0.0.0:4000"

tls:
  key_path: "../certs/brachyura.key"
  cert_path: "../certs/brachyura.crt"

timeout: 1000

backends:
  - name: "test.home"
    location: "127.0.0.1:8000"
  - name: "origin.home"
    location: "127.0.0.1:10000"
  - name: "pihole.home"
    location: "192.168.1.250"
  - name: "test-lb.home"
    backend_type: "loadbalanced"
    locations:
      - "127.0.0.1:10000"
      - "127.0.0.1:10001"
