listen: "0.0.0.0:4000"

tls:
  key_path: "tests/self-signed-cert/test.key"
  cert_path: "tests/self-signed-cert/test.crt"

timeout: 1000

backends:
  - name: "prometheus.home"
    location: "127.0.0.1:9090"
  - name: "grafana.home"
    location: "127.0.0.1:3000"
  - name: "backend.home"
    location: "127.0.0.1:10000"
  - name: "test-lb.home"
    backend_type: "loadbalanced"
    locations:
      - "127.0.0.1:10000"
      - "127.0.0.1:10001"
