listen: "127.0.0.1:4000"

tls:
  enabled: true
  key_path: "../certs/key"
  cert_path: "../certs/cert.crt"

backends:
  - name: "test.home"
    location: "127.0.0.1:8000"
  - name: "origin.home"
    location: "127.0.0.1:10000"
  - name: "pihole.home"
    location: "192.168.1.250"
