global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s
scrape_configs:
  - job_name: "brachyura"
    scheme: https
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:4000"]
    tls_config:
        insecure_skip_verify: true
    http_headers:
      x-no-proxy:
        values: ["true"]