{
 "title": "Proxied Traffic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Proxied traffic metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS by backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (backend_name)",
     "legendFormat": "{{backend_name}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[10s])) by (backend_name, le))",
     "legendFormat": "{{backend_name}}"
    }
   ]
  },
  {
   "title": "In flight requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "http_requests_in_flight", "legendFormat": "in flight" }
   ]
  }
 ]
}